import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGenerated1730358528490 implements MigrationInterface {
  name = 'AutoGenerated1730358528490';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."messages_status_enum" AS ENUM('active', 'pending', 'spam', 'deleted')`,
    );
    await queryRunner.query(
      `CREATE TABLE "messages" ("id" SERIAL NOT NULL, "message" character varying NOT NULL, "status" "public"."messages_status_enum" NOT NULL DEFAULT 'pending', "translations" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "messages"`);
    await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
  }
}
